---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: centos-5.11
- name: centos-6.6
- name: centos-7.0
- name: debian-6.0.10
- name: debian-7.8
- name: fedora-19
  driver_config:
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-19_chef-provisionerless.box
- name: fedora-20
- name: fedora-21
# FreeBSD platform requires to run kitchen verify twice by hand
# - name: freebsd-9.2
# - name: freebsd-10.0
- name: opensuse-13.1-x86_64
  driver_config:
    box: opscode-opensuse-13.1
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_opensuse-13.1-x86_64_chef-provisionerless.box
- name: ubuntu-10.04
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: ubuntu-14.10

suites:
- name: default
  run_list:
  - recipe[ssh_authorized_keys_test::default]
