name 'github-awards'
maintainer 'vdaubry'
maintainer_email 'vdaubry@gmail.com'
license 'all_rights'
description 'Installs/Configures github-awards'
long_description 'Installs/Configures github-awards'
version '0.1.0'

depends 'apt',                  '~> 2.9.2'
depends 'ssh_authorized_keys',  '~> 0.3.0'
depends 'line',                 '~> 0.6.3'
depends 'swap',                 '~> 0.3.8'
depends 'postgresql',           '~> 4.0.0'